### ISSUE TITLE
Differentiate "test/" Branches by SHA

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-desktop-gh-bridge#19]
At present, the Calypso bridge works by branching off current wp-desktop `develop` HEAD SHA with branch name `test/<calypso-branch-name>`. Within each CI job that's kicked off on the `test/` branch, the corresponding (unique) Calypso submodule SHA is checked out and tested. However, the SHA of all `test/` branches is identical!

What this means if CI is running concurrently across multiple `test/` branches, a failure in one branch will automatically be propagated to the current jobs of other branches with the same SHA (including `develop` itself). This can end up giving an incorrect signal regarding the status of each branch, as well as `develop`. 

<p align="center">
<img width="1046" alt="test-branches-same-sha" src="https://user-images.githubusercontent.com/8979548/75460728-d2ac0a00-594f-11ea-8b61-cbc33e74d030.png">
</p>

To address this, I propose the following:

- [ ] When each `test/` branch is created, amend the branch so it has a unique SHA (perhaps the Github  [Contents](https://developer.github.com/v3/repos/contents/) API might be helpful in this regard)
- [ ] Run a nightly job of the tip of wp-desktop `develop` branch against the tip of Calypso `master`. 

The above changes would ensure that (i) the status of Calypso PRs (as reflected in the `test/` branch) does not interfere with other PRs, and (ii) the build status of the all merged changes into Calypso and wp-desktop is periodically vetted as well.

**Comment by nsakaimbo** [comment]
@bsessions85 Not urgent, but would appreciate any feedback you may have here. I'm not sure how far off the monorepo work is w.r.t wp-desktop, but while that's still up in the air this would be a useful change.

**Comment by bsessions85** [comment]
@nsakaimbo Yeah, I think it would be worth getting this done. I think the nightly job work would be done in the wp-desktop repo, but we can confirm that when we start this work. I'll add it to the DevEx.Quality backlog.
